- hosts: all
  tasks:
    - yum: name=* state=latest

    - yum: name={{item}} state=installed
      with_items:
      - "git"
      - "@Development tools"
      - "zlib-devel"
      - "bzip2-devel"
      - "openssl-devel"
      - "ncurses-devel"
      - "sqlite-devel"
      - "readline-devel"
      - "tk-devel"

    - get_url: url="https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz" validate_certs=no dest=/tmp

    - command: tar xf Python-2.7.6.tar.xz
      args:
        chdir: /tmp
        creates: /tmp/Python-2.7.6

    - shell: ./configure --prefix=/usr/local && /usr/bin/make && /usr/bin/make altinstall
      args:
        chdir: /tmp/Python-2.7.6
        creates: /usr/local/bin/python2.7

    - easy_install: name=pip state=present

    - pip: name={{ item }}
      with_items:
      - "awscli"
      - "boto"
      - "boto3"