- hosts: all
  tasks:
    - yum: name=git state=installed

    - easy_install: name=pip state=present

    - pip: name={{ item }}
      with_items:
        - "awscli"
        - "boto"
        - "boto3"