- name: Include git repos to be setup
  include_vars: "git_repos.yml"

- name: Checkout repo
  git:
    repo: "{{item.git_url}}"
    dest: "{{item.guest_dest_folder}}"
  with_items: "{{repos}}"

- name: NPM Install
  npm:
    path: "{{item.guest_dest_folder}}"
    state: latest
  with_items: "{{repos}}"