Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "openSUSE"
  config.vm.box_url = "../openSUSE.box"

  vagrant_folder = "/vagrant/playbooks"
  config.vm.synced_folder "../nodejs/playbooks", vagrant_folder, :nfs => true
  config.vm.synced_folder "../../../node_projects", '/opt/node_projects', :nfs => true
  config.vm.network :private_network, ip: "192.168.51.5"
  config.vm.network "forwarded_port", guest: 8080, host: 8090
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "#{vagrant_folder}/provision.yml"
    ansible.sudo = true
    ansible.verbose = "vvvv"
  end

end
